name: Unittest
on: pull_request:
    branvhes:
        - main
jobs:
    unittest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo "Success"